# Generated by Django 5.1.1 on 2024-11-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_name_student_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='surname',
        ),
    ]
