# Generated by Django 5.1.1 on 2024-11-21 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_room_schedule_remove_student_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='gps_location',
        ),
        migrations.RemoveField(
            model_name='class',
            name='students',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='school',
            name='gps_coordinates',
        ),
        migrations.RemoveField(
            model_name='student',
            name='attendance_records',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_info',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='schedule',
        ),
        migrations.AddField(
            model_name='attendance',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AddField(
            model_name='grade',
            name='term',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AddField(
            model_name='school',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(related_name='students', to='app.class'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='app.student'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='participants',
            field=models.ManyToManyField(related_name='calendar_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classes', to='app.teacher'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.room'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_value',
            field=models.CharField(choices=[('5', 'Excellent'), ('4', 'Good'), ('3', 'Satisfactory'), ('2', 'Unsatisfactory')], max_length=1),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='app.student'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='access_privileges',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(related_name='parents', to='app.student'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='contact_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_records',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='medical_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(related_name='teachers', to='app.subject'),
        ),
    ]
